### ISSUE TITLE
Does not work when cloning from branches other than master

### ISSUE THREAD

**Issue by dianashk** [pelias/vagrant#37]
We are currently using the `master` branch to host the in-progress release. It is not appropriate for consumption at certain times, and we should be using the `production` branches across all the components to avoid problems for external users.

Particularly, changing the branches specified on the following lines (and other relevant ones that I may have missed here)

https://github.com/pelias/vagrant/blob/master/cookbooks/pelias/attributes/default.rb#L26
https://github.com/pelias/vagrant/blob/master/cookbooks/pelias/attributes/default.rb#L37
https://github.com/pelias/vagrant/blob/master/cookbooks/pelias/attributes/default.rb#L50
https://github.com/pelias/vagrant/blob/master/cookbooks/pelias/attributes/default.rb#L71
https://github.com/pelias/vagrant/blob/master/cookbooks/pelias/attributes/default.rb#L80

**Comment by easherma** [comment]
When trying to use the vagrant repo to pull from the production branches, I get these errors:

>=> default: Running handlers:
==> default: [2016-02-19T19:08:27+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-02-19T19:08:27+00:00] ERROR: Exception handlers complete
==> default: [2016-02-19T19:08:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: Chef Client failed. 100 resources updated in 240.133574018 seconds
==> default: [2016-02-19T19:08:27+00:00] ERROR: runit_service[pelias-address-deduper] (pelias::_address_deduper_service line 8) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of /usr/bin/sv -w '60' restart /etc/service/pelias-address-deduper ----
==> default: STDOUT: timeout: down: /etc/service/pelias-address-deduper: 0s, normally up, want up
==> default: STDERR:
==> default: ---- End output of /usr/bin/sv -w '60' restart /etc/service/pelias-address-deduper ----
==> default: Ran /usr/bin/sv -w '60' restart /etc/service/pelias-address-deduper returned 1
==> default: [2016-02-19T19:08:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Output of the stacktrace dump:

>Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/exceptions.rb:225:in raise!' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:104:inrun_delayed_notifications'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:88:in converge' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/client.rb:345:inconverge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/client.rb:431:in do_run' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/client.rb:213:inblock in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/client.rb:207:in fork' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/client.rb:207:inrun'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application.rb:217:in run_chef_client' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application/solo.rb:221:inblock in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application/solo.rb:213:in loop' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application/solo.rb:213:inrun_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application.rb:67:in run' /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/bin/chef-solo:25:in<top (required)>'
