### ISSUE TITLE
Unable to import OpenAddresses data

### ISSUE THREAD

**Issue by pjsier** [pelias/vagrant#39]
I have the API working from localhost:3100, but when I post the query to `http://localhost:3100/v1/search?sources=oa&text=216+W+QUINCY+CHICAGO,+IL` I get the following empty response

```json
{"geocoding":{"version":"0.1","attribution":"http://pelias.mapzen.com/v1/attribution","query":{"text":"216 W QUINCY CHICAGO, IL","parsed_text":{"name":"216 W QUINCY CHICAGO","state":"IL","regions":["216 W QUINCY CHICAGO"],"admin_parts":"IL"},"types":{"from_sources":["openaddresses"]},"size":10,"private":false,"type":["openaddresses"],"querySize":20},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1456524586352},"type":"FeatureCollection","features":[]}
```

The OpenAddresses dataset I'm using is for the city of Chicago, http://s3.amazonaws.com/data.openaddresses.io/runs/63513/us/il/city_of_chicago.zip

Additionally, when I try to manually run the OpenAddresses import from [pelias/openaddresses](https://github.com/pelias/openaddresses) I get minimal output:

```
vagrant@pelias:~/openaddresses$ node import.js ../my_dataset
2016-02-26T22:11:00.466Z - info: [openaddresses] Importing 1 files.
2016-02-26T22:11:02.200Z - info: [openaddresses] Creating read stream for: ../my_dataset/city_of_chicago.csv
2016-02-26T22:16:33.473Z - info: [openaddresses] Total time taken: 333.012s
```

**Comment by orangejulius** [comment]
Hey @pjsier,
That openaddress import output looks right for a run with no debugging info turned on. Unfortunately it looks like that address isn't in the OpenAddresses data for Chicago, so that's probably why you got no results.

Try this query: `http://localhost:3100/v1/search?text=2714 W lexington, chicago`

**Comment by pjsier** [comment]
@orangejulius thanks for the reply! You're right, I think I was getting confused because when I add `sources=oa` or `layers=address`, it returns an empty response. But when I search without either of those options it still returns data from those sources. Is this intentional?

**Comment by orangejulius** [comment]
Hm, that might be due to some current turmoil on our master branch of the API code. Try this branch: https://github.com/pelias/api/tree/new_wof_model_format

Also, I meant to mention last time. You can get more output during imports by adding some logging settings in your `pelias.json` config file (it's in `/etc/pelias` on the vagrant image). Here's what I have:

```
    "logger": {
        "level": "debug",
        "timestamp": true
    },
```

**Comment by pjsier** [comment]
Great, in that case I think this issue can be closed. The only thing that might be worth adding is the logging settings to the README (unless they're there and I just missed them).

**Comment by orangejulius** [comment]
Thanks @pjsier, I've made a note in one of our documentation tickets (pelias/pelias-doc#81) to remember to put a note about logging in the right place. Let us know if you have more questions.
